import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/molecules/Header";
import { ThemeProvider } from "@/components/ThemeProvider";
import AuthProvider from "@/components/AuthProvider";
import FirebaseAuthProvider from "@/components/FirebaseAuthProvider";
import { Toaster } from "react-hot-toast";
import SubscriptionProvider from "@/components/SubscriptionProvider";

const inter = Inter({ subsets: ["latin"] });
const nunito = Nunito({
  subsets: ['latin'],
  variable:"--font-nunito"
});


export const metadata: Metadata = {
  title: "Chat Flex",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <AuthProvider>
    <html lang="en" >
      <body className={nunito.className}>
        <FirebaseAuthProvider>
          <SubscriptionProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
            >
              <Header />
              {children}
              <Toaster/>
            </ThemeProvider>
          </SubscriptionProvider>
        </FirebaseAuthProvider>
      </body>
    </html>
  </AuthProvider>
  );
}
